Better install experience
githedgehog/fabricator pull request #147
Opened 2024-09-26 18:14 UTC by mrbojangles3

2024-09-26 19:53 UTC, Frostman requested changes
Added some initial comments

2024-09-26 19:53 UTC, Frostman commented on pkg/fab/flatcar/iso/build.go
> +		slog.Error("CopyFile Error Opening Source Path", "SourcePath", srcPath, "Error:", err.Error())
We shouldn't ignore such errors, plus let's use fmt.Errorf to wrap errors, please. I wrote you in slack to have chat about it.

2024-09-26 19:53 UTC, Frostman commented on pkg/fab/flatcar/iso/build.go
> +	diskLogan, err := diskfs.Create(diskImg, diskSize, diskfs.Raw, diskfs.SectorSizeDefault)
"diskLogan"

2024-09-26 19:53 UTC, Frostman commented on pkg/fab/flatcar/iso/build.go
> +	err = copyFile("/", workdir+"/flatcar_production_pxe_image.cpio.gz", espFs)
each error should be handled

2024-09-27 02:40 UTC, Frostman commented on pkg/fab/ctrl_os_butane.tmpl.yaml
> +        ConditionFirstBoot=yes
I'm wondering if installer failed on first attempt for some reason, do we want to re-run it automatically? Would first boot handle it?

2024-09-27 18:18 UTC, mrbojangles3 commented on pkg/fab/flatcar/iso/build.go
> +	diskLogan, err := diskfs.Create(diskImg, diskSize, diskfs.Raw, diskfs.SectorSizeDefault)
lol, ah yeah. Forgot to clean that up.

2024-09-27 18:48 UTC, mrbojangles3 commented on pkg/fab/ctrl_os_butane.tmpl.yaml
> +        ConditionFirstBoot=yes
While it is technically possible to re-run if the installer fails for some reason it would be terrible UX. 
We can change this unit file to run conditionally on the existence of a file for example `/opt/hedgehog/install-done` and if the install fails for some reason we can instruct the user to delete that file then re-run the unit file with `systemctl start fabric-install.service` or some nicer shell script with that in it.

2024-10-01 02:57 UTC, Frostman commented
Installer ISO build is merged into hhfab-v2 branch as https://github.com/githedgehog/fabricator/pull/148/commits/65afe2c04fb683b0408ffd96c905c644adeba1ac

2024-10-08 17:41 UTC, closed without merging

2024-10-08 17:41 UTC, Frostman commented
Merged as part of other PRs