Minor improvs to hhnet script
githedgehog/fabricator pull request #230
Opened 2024-11-25 12:31 UTC by edipascale

* set down interface before enslaving it, to prevent errors if it is already up
* limit the attempts in get_ip to 30 to avoid stalling forever

2024-11-26 18:08 UTC, Frostman requested changes
thx, it totally makes sense to down interface just in case and not wait forever for IP from DHCP

2024-11-26 18:08 UTC, Frostman commented on pkg/hhfab/hhnet.sh
> +    local max_attempts=30
let's set it to a minute just to be on a safe side, thank you

2024-11-26 20:23 UTC, edipascale commented on pkg/hhfab/hhnet.sh
> +    local max_attempts=30
done, thanks!

2024-11-26 20:32 UTC, mrbojangles3 commented
After this passes CI, it looks good to me.

2024-12-02 17:04 UTC, Frostman approved these changes

2024-12-02 17:05 UTC, merged