Correct some messages
githedgehog/fabricator pull request #231
Opened 2024-11-25 16:16 UTC by pau-hedgehog

Correct some usage messages and a log message

2024-11-26 18:05 UTC, Frostman requested changes
thanks for picking it up!

2024-11-26 18:05 UTC, Frostman commented on cmd/hhfab/main.go
> +				Usage:  "validate config and include wiring files",
it validates config and validated included wiring files, should be reworded probably

2024-11-26 18:05 UTC, Frostman commented on pkg/fab/recipe/control_build.go
> +	slog.Info("Adding config and including wiring to installer", "control", b.Control.Name)
ditto

2024-11-26 22:07 UTC, pau-hedgehog commented on cmd/hhfab/main.go
> +				Usage:  "validate config and include wiring files",
Changed to `"validate config and wiring files"`

2024-11-26 22:07 UTC, pau-hedgehog commented on pkg/fab/recipe/control_build.go
> +	slog.Info("Adding config and including wiring to installer", "control", b.Control.Name)
Changed to `Adding config and wiring files to installer`

2024-12-02 17:08 UTC, Frostman commented on cmd/hhfab/main.go
> +			        Usage: "operate Virtual Lab",
it's a wrong indent here (mix of tabs and spaces)

2024-12-02 17:27 UTC, Frostman commented on cmd/hhfab/main.go
> +			        Usage: "operate Virtual Lab",
sorry, it wasn't caught by CI b/c of the https://github.com/githedgehog/fabricator/pull/238

2024-12-03 13:14 UTC, pau-hedgehog commented on cmd/hhfab/main.go
>  				Name: "vlab",
Fixed. Thanks for the hint

2024-12-03 16:04 UTC, Frostman approved these changes

2024-12-03 16:05 UTC, merged