add hhfab options for power management
githedgehog/fabricator pull request #256
Opened 2024-12-09 15:46 UTC by pau-hedgehog

add switch CLI suboptions to vlab for power management

2024-12-12 22:35 UTC, Frostman requested changes

2024-12-12 22:35 UTC, Frostman commented on pkg/pdu-mgt/go.mod
> +module go.githedgehog.com/fabricator/pkg/pdu-mgt
There is no need for a separate module. It only adds some complications. Could you please move the code to somewhere under pkg/hhfab like pkg/hhfab/pdu

2024-12-12 22:35 UTC, Frostman commented on pkg/pdu-mgt/utils/utils.go
> +func ConfirmActions(action string, outlets map[string]string) bool {
There are a few places where we're using --yes flag in such cases in a CLI, I think it'll be better to keep that approach consistent across CLIs. Last example is https://github.com/githedgehog/fabric/pull/690

2024-12-12 22:35 UTC, Frostman commented on pkg/pdu-mgt/utils/utils.go
> +	return parts[2]
it'll panic if len(parts) < 0, so it needs a check

2024-12-12 22:35 UTC, Frostman commented on pkg/pdu-mgt/utils/utils.go
> +		log.Fatalf("Error extracting outlet ID: %v", err)
error should be returned or handled

2024-12-12 22:35 UTC, Frostman commented on cmd/hhfab/main.go
> +										Usage:   "name of the switch to reinstall, or use '--all' for all switches",
I think it'll be better to have a separate bool flag `--all` so it's an explicit flag

2024-12-12 22:35 UTC, Frostman commented on cmd/hhfab/main.go
> +									if c.NArg() < 1 {
I think stricter check (!=1) would allow to avoid unexpected behaviour

2024-12-12 22:35 UTC, Frostman commented on cmd/hhfab/main.go
> +									powerAction := c.Args().First()
maybe wrap with strings.ToUpper just in case

2024-12-13 00:14 UTC, Frostman commented on pkg/pdu-mgt/go.sum
> +github.com/joho/godotenv v1.5.1 h1:7eLL/+HRGLY0ldzfGMeQkb7vMd0as4CfYvUVzLqw0N0=
It doesn't look like it's used anywhere

2024-12-13 11:59 UTC, pau-hedgehog commented on pkg/pdu-mgt/go.mod
> +module go.githedgehog.com/fabricator/pkg/pdu-mgt
Thanks for the hint. Yes gave me more than one headache.

Addressed

2024-12-13 12:00 UTC, pau-hedgehog commented on pkg/pdu-mgt/utils/utils.go
> +func ConfirmActions(action string, outlets map[string]string) bool {
Addressed taking the approach from fabric

2024-12-13 12:39 UTC, pau-hedgehog commented on pkg/pdu-mgt/utils/utils.go
> +	return parts[2]
addressed

2024-12-13 12:39 UTC, pau-hedgehog commented on pkg/pdu-mgt/utils/utils.go
> +		log.Fatalf("Error extracting outlet ID: %v", err)
addressed

2024-12-13 12:40 UTC, pau-hedgehog commented on pkg/pdu-mgt/go.sum
> +github.com/joho/godotenv v1.5.1 h1:7eLL/+HRGLY0ldzfGMeQkb7vMd0as4CfYvUVzLqw0N0=
removed as it's been integrated in hhfab

2024-12-13 17:21 UTC, pau-hedgehog commented on cmd/hhfab/main.go
> +										Usage:   "name of the switch to reinstall, or use '--all' for all switches",
addressed

2024-12-13 17:22 UTC, pau-hedgehog commented on cmd/hhfab/main.go
> +									if c.NArg() < 1 {
addressed

2025-01-02 22:30 UTC, pau-hedgehog commented on cmd/hhfab/main.go
> +										Usage:   "name of the switch to reinstall, or use '--all' for all switches",
...and fixed now for power operations

2025-01-13 23:21 UTC, pau-hedgehog commented
After discussing, the default behavior needs to change and reinstall must leave the switches in the ONIE install loop.

The initial behavior will be preserved with a flag `--wait-ready` that will be relayed to the GRUB script.

2025-01-14 07:43 UTC, pau-hedgehog commented
> After discussing, the default behavior needs to change and reinstall must leave the switches in the ONIE install loop.
> 
> This way one can trigger the reinstall and then do the `vlab up`. Once the control node is ready, the switches will be finally reinstalled.
> 
> The initial behavior will be preserved with a flag `--wait-ready` that will be relayed to the GRUB script.

I tried this but hhfab requires vlab up:
```
ubuntu@env-1:~/hhfab$ ./hhfab-pow-reinst vlab switch reinstall --all --yes 
07:37:04 INF Hedgehog Fabricator version=v0.32.1-21-gec342fd8-dirty-a72344
Enter username: admin
Enter password: 
07:37:10 INF Wiring hydrated successfully mode=if-not-present
07:37:10 ERR reinstall failed: preparing VLAB: VLAB directory does not exist: "/home/ubuntu/hhfab/vlab"
```

Shall we go with the original approach, @Frostman ?

2025-01-15 19:40 UTC, Frostman approved these changes

2025-01-15 19:41 UTC, merged