Server lldp and control vm installation error handling
githedgehog/fabricator pull request #289
Opened 2024-12-27 11:44 UTC by pau-hedgehog

Some changes as part of needs/issues I've been finding

Open to discuss as I may be forcing the devel workflow in ways not supported

2024-12-27 23:52 UTC, Frostman commented on hack/tools.just
> +skopeo_dest_insecure := if oci == "http" { "" } else { "--dest-tls-verify=false" }
the `else` branch is supposed to be "secure", what are you trying to achieve?

2024-12-27 23:52 UTC, Frostman commented on hack/tools.just
> +  {{helm}} push --insecure-skip-tls-verify config/helm/{{name}}-{{version}}.tgz oci://{{oci_repo}}/{{oci_prefix}}/charts
same - default behaviour should be secure

2024-12-27 23:58 UTC, Frostman requested changes

2024-12-27 23:58 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +            ExecStartPost=/bin/systemctl restart systemd-resolved
Why? It looks kinda strange

2024-12-27 23:58 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - name: lldpd.service
It would be better to enable LLDP through the systemd-networkd which is used for the interfaces configurations, we already have it for the mgmt interface - https://github.com/githedgehog/fabricator/blob/135b17c8fd155df192caad131e657f5ede98035e/pkg/fab/recipe/control_butane.tmpl.yaml#L106-L107 

I think something like but applied to all interfaces would be a good approach (together with DHCP, check the 99-default file (or similar name)

2024-12-27 23:58 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - path: /etc/systemd/resolved.conf.d/custom-dns.conf
We shouldn't configure DNS by default as we're testing a DHCP server feature to propagate specified DNS servers. Check `--dns` flag for `hhfab vlab setup-vpcs`

2024-12-27 23:58 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - path: /etc/lldpd.conf
Woudn't be required if using systemd-networkd LLDP

2024-12-27 23:58 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +        ExecStart=/usr/sbin/lldpd -d
Hm, I don't think it's available on the flatcar

2024-12-31 19:54 UTC, Frostman commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - path: /etc/systemd/network/enp2s1.network
probably something like 

```
[Match]
Name=en*

[Network]
DHCP=yes
LLDP=yes
EmitLLDP=yes
```

in `/etc/systemd/network/99-wildcard.network` would be more generic and will make sure DHCP is always enabled as well (number prefix is generally recommended for drop-ins)

2024-12-31 22:20 UTC, pau-hedgehog commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - path: /etc/systemd/network/enp2s1.network
Had tried wildcards without success. But I've tried this and works like a charm. Thanks!

2025-01-02 20:24 UTC, pau-hedgehog commented on pkg/hhfab/vlab_butane.tmpl.yaml
> +    - path: /etc/systemd/network/enp2s1.network
I was facing issues with this approach. The fact that servers are sending LLDP on both the physical and the vlan interfaces is not welcomed by the sonic counterpart

2025-01-07 16:23 UTC, Frostman approved these changes

2025-01-07 16:23 UTC, merged